apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-0-data-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-0-data-0
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-0/data-0
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-0-data-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-0-data-1
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-0/data-1
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-0-data-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-0-data-2
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-0/data-2
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-1-data-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-1-data-0
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-1/data-0
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-1-data-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-1-data-1
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-1/data-1
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-1-data-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-1-data-2
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-1/data-2
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-2-data-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-2-data-0
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-2/data-0
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-2-data-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-2-data-1
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-2/data-1
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-broker-2-data-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pv-kafka-broker-2-data-2
    volumeAttributes:
      source: //192.168.20.99/kubernetes/kafka
      subDir: broker-2/data-2
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kafka
