apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller-node-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  resources:
    requests:
      memory: 1Gi
      cpu: "0.5"
    limits:
      memory: 2Gi
      cpu: "1"
  storage:
    type: ephemeral
  roles:
    - controller
