apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka-smb-test
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-kafka-smb-test
  storageClassName: ""
