#!/bin/bash
# Script to upload multiple images to Harbor

IMAGES=(
    "elasticsearch 7.10"
    "elasticsearch 8.0"
    "kibana 7.10"
    "kibana 8.0"
    "logstash 7.10"
    "logstash 8.0"
    "prometheus latest"
    "grafana latest"
    "influxdb 1.8"
    "influxdb 2.0"
    "telegraf latest"
    "chronograf latest"
    "kapacitor latest"
    "consul 1.10"
    "consul 1.11"
    "vault 1.8"
    "vault 1.9"
    "etcd 3.5"
    "zookeeper 3.7"
    "cassandra 3.11"
    "cassandra 4.0"
    "couchdb 3.1"
    "couchdb 3.2"
    "memcached 1.6"
    "memcached 1.7"
    "haproxy 2.4"
    "haproxy 2.5"
    "traefik 2.5"
    "traefik 2.6"
    "nginx 1.20"
    "nginx 1.21"
    "nginx 1.22"
    "apache 2.4"
    "varnish 6.0"
    "varnish 7.0"
    "squid latest"
    "bind9 latest"
    "postfix latest"
    "dovecot latest"
    "openldap latest"
    "389ds latest"
    "389ds 2.0"
    "389ds 2.1"
    "389ds 2.2"
    "389ds 2.3"
    "389ds 2.4"
    "389ds 2.5"
    "389ds 2.6"
    "389ds 2.7"
    "389ds 2.8"
    "389ds 2.9"
    "389ds 3.0"
)

for item in "${IMAGES[@]}"; do
    IMAGE=$(echo $item | cut -d' ' -f1)
    TAG=$(echo $item | cut -d' ' -f2)
    echo "Processing $IMAGE:$TAG..."
    ./scripts/1.sh "$IMAGE" "$TAG"
    ./scripts/2.sh "$IMAGE" "$TAG"
    ./scripts/3.sh "$IMAGE" "$TAG"
    ./scripts/4.sh "$IMAGE" "$TAG"
    ./scripts/5.sh "$IMAGE" "$TAG"
    echo "Done with $IMAGE:$TAG"
done