x-resources-build: &resources_build
  build:
    context: .
    dockerfile: docker/Dockerfile.worker.gpu

x-resources: &resources_cpu
  <<: *resources_build
  privileged: true
  tmpfs:
    - /tmp
    - /run
  restart: always
  environment:
    - DOCKER_TLS_CERTDIR=/certs
    - SSH_AUTH_SOCK=/ssh-agent
    - TZ=Europe/Madrid

services:
  dispatcher:
    build:
      context: .
      dockerfile: docker/Dockerfile.dispatcher_ssh
    ports:
      - "50422:22"
    restart: always

  worker:
    <<: *resources_cpu
    volumes:
      - ./docker/images:/data/images
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - /var/lib/docker
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools

networks:
  default:
    name: diun
    external: true

volumes:
  worker_data: