services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx.portinaer_ttyd
    depends_on:
      - worker
    ports:
      - "50426:80"
      - "50427:443"
    environment:
      - SCALE=5
    restart: unless-stopped

networks:
  default:
    name: diun
    external: true

volumes:
  worker_data:
  worker_docker: