apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: milvus

resources:
- 00-namespace.yaml
- 01-storage.yaml
- 02-configs.yaml
- 10-etcd.yaml
- 11-minio.yaml
- 20-milvus.yaml
- 30-prometheus.yaml
- 31-grafana.yaml
- 40-attu.yaml
