build:
	docker-compose build

start:
	docker-compose up -d

stop:
	docker-compose down

into:
	docker-compose exec agy zsh

run:
	docker run --rm -it wisrovi/agy-edc:v1.2.0 zsh

publish:
	docker push wisrovi/agy-edc:v1.2.0
