input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [container] {
    mutate {
      add_field => { "service" => "%{container}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}