server {
    listen 80;
    server_name localhost;

    location / {
        auth_basic           "Zona restringida";
        auth_basic_user_file /etc/nginx/auth/htpasswdp;
        proxy_pass http://server1:80;
    }

    location /public {
        proxy_pass http://server1:80;
    }

    location /health {
        allow all;
        access_log off;
        return 200 'OK';
    }
}
