version: '3'

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    volumes:
      - ./folder_sharing:/data
      - ./config:/config
    ports:
      - 4443:8080
    environment:
      - PUID=1000
      - PGID=1000
    #  - TZ="Asia/Shanghai"
      - FB_BASEURL=/
      - VIRTUAL_HOST=wisrovi.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=wisrovi.com
      - LETSENCRYPT_EMAIL=wisrovi.rodriguez@gmail.com
    restart: always
