[tool.poetry]
name = "imagenesdocker"
version = "0.1.0"
description = ""
authors = ["williamrv-edt <138199553+williamrv-edt@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.5"
python-dotenv = "^1.1.1"
pandas = "^2.3.2"
notebook = "^7.4.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
