version: "2.1"
services:
  duckdns:
    image:  linuxserver/duckdns:amd64-version-3a3dda8a
    #image:  linuxserver/duckdns:arm32v7-version-e60b35ff
    container_name: duckdns
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/London
      - SUBDOMAINS=kafkawisrovi, wisrovi
      - TOKEN=febef3d7-8582-4373-909b-94f62b477906
      - LOG_FILE=false 
    volumes:
      - ./appdata/config:/config l
    restart: unless-stopped