# https://smarthomepursuits.com/how-to-install-snippet-box-in-docker/

version: '3'
services:
  snippet-box:
    image: pawelmalak/snippet-box:arm
    container_name: snippet-box
    privileged: true
    volumes:
      - ./data:/app/data
    ports:
      - 5000:5000
    restart: unless-stopped