version: "3.3"

services:
  kurento:
    image: kurento/kurento-media-server:6.16.0
    hostname: kurento
    container_name: kurento
    volumes:
      - ./etc/:/etc/kurento/"
      - ./lib/:/var/lib/
    expose:
      - "8888"
    ports:
      - 8888:8888