version: '3.8'

services:
  agents:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    image: wisrovi/agents:cpu
    container_name: agents
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:ro
    stdin_open: true
    tty: true
    command: zsh