
# Docker Compose file for setting up a Jenkins environment.
version: '3.8'
services:
  jenkins:
    # Sets the container name for easy reference.
    container_name: jenkins
    # Specifies the build context and Dockerfile for creating the Jenkins image.
    build:
      context: .
      dockerfile: Dockerfile
    # Names the image that will be built.
    image: wisrovi/jenkins/pipelines:latest
    # Maps the host port 50443 to the container port 8080 for accessing the Jenkins web UI.
    ports:
      - 50443:8080  # Jenkins web port
      # - 50000:50000  # Port for Jenkins agents (if you need them)
    # Defines volumes for data persistence and host interaction.
    volumes:
      # Shares a host directory with the container for managing Git projects.
      - /home/wisrovi/projects:/home/projects

      # Persists Jenkins configuration and data.
      - ./jenkins_home:/var/jenkins_home

      # Allows Jenkins to interact with the Docker daemon on the host.
      - /var/run/docker.sock:/var/run/docker.sock

      # Shares SSH keys with the container for Git authentication.
      - ~/.ssh:/root/.ssh
    # Runs the container as the root user.
    user: root
    # Grants the container extended privileges, necessary for Docker-in-Docker.
    privileged: true
    # Ensures the container restarts automatically unless manually stopped.
    restart: always
    # Sets the time zone for the container.
    environment:
      - TZ=Europe/Madrid

# Useful commands for managing the Jenkins container:
#
# Get the initial admin password:
#   docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword
#
# Get the container's IP address:
#   docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jenkins
#
# Access the container's shell:
#   docker exec -it jenkins /bin/bash
#
# Access the container's shell as root:
#   docker exec -it -u root jenkins /bin/bash
