version: '3.8'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    image: wisrovi/jenkins/pipelines:latest
    ports:
      - 50443:8080  # Puerto web de Jenkins
      # - 50000:50000  # Puerto para agentes Jenkins (si los necesitas)
    volumes:
      # para compartir la carpeta donde git podra gestionar los proyectos (eg. clonar un repo y despegarlo)
      - /home/wisrovi/projects:/home/projects

      # para hacer perpetua la configuracion de jenkins
      - ./jenkins_home:/var/jenkins_home

      # para docker
      - /var/run/docker.sock:/var/run/docker.sock   # Permite a Jenkins interactuar con Docker en el host

      # Para git
      - ~/.ssh:/root/.ssh   # para compartir mis llaves de SSH desde un folder personalizado y permite a Jenkins interactuar con git en el host
      # - ~/.ssh/:/root/.ssh  # Monta el directorio SSH para acceso a repositorios privados desde git y permite a Jenkins interactuar con git en el host
    user: root
    privileged: true
    restart: always # Reinicia Jenkins automáticamente a menos que lo detengas manualmente
    environment:
      - TZ=Europe/Madrid # Ajusta la zona horaria a tu ubicación

# https://blog.295devops.com/cicd-the-series-aprende-a-crear-tu-primer-pipeline-de-jenkins-con-roxs
# pluggins recomendados:
# - Docker Pipeline Plugin: Docker en tu flujo de trabajo
# - Blue Ocean Plugin: una interfaz más moderna
# - GitHub Plugin: para disparar pipelines cuando hayan merge en ramas
# - SonarQube Scanner Plugin: para escaner de codigo automatizado