apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-worker1
spec:
  nodeSelector:
    worker: worker1
  restartPolicy: Never
  containers:
  - name: gpu-container
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    command: ["nvidia-smi"]