version: "3"
services: 
    tomcat:
        container_name: miproyecto-tomcat
        build: ./tomcat-8.5
        ports:
            - 8080:8080
        volumes:
            - D:\apache-tomcat\tomcat-war:/usr/local/tomcat/webapps

    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - D:\apache-tomcat\database-mongo:/data/db
        ports:
            - 27017:27017
        restart: always