apiVersion: v1
kind: Service
metadata:
  name: attu
  namespace: milvus
  labels:
    app: attu
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 3000
      nodePort: 30004
  selector:
    app: attu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attu
  namespace: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
      - name: attu
        image: zilliz/attu:v2.6.0
        env:
        - name: MILVUS_URL
          value: "milvus-standalone.milvus.svc.cluster.local:19530"
        ports:
        - containerPort: 3000
