
server {
    listen 8300 ssl;
    server_name www.arepo.perfil.com;

    client_max_body_size 250M;

    # SSL
    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # security for SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;

    # add HSTS for to force https
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    location /wisrovi/api/gpu {
        # Error page custom for 502 Bad Gateway
        error_page 502 /50x.html;

        # proxy for FastAPI backend
        proxy_pass http://10.43.71.205:80;

        # Headers for proxying requests to the FastAPI backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;            

        # Timeout for proxying requests to the FastAPI backend
        proxy_read_timeout 360s;

        # Headers for WebSocket support (if needed in the future)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    

    # Ubicación de la página de error personalizada
    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }

}
