# Generated by Django 4.1 on 2022-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=20)),
                ('path_instalation', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
