# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.7'
services:
  webservice:
      container_name: password_generator
      image: password_generator:V1.0
      #volumes:
      #    - config:/local_aplication/local_aplication/config/general:ro      
      #ports:
      #   - 5050:80
      deploy:
         resources:
           limits:
             cpus: "0.50"
             memory: 512M
           reservations:
             cpus: "0.25"
             memory: 128M
      restart: always
      privileged: true

  nginx:
      # Defino el nombre del contenedor que tendra el NGINX
      container_name: webservice_nginx
      
      # Defino la imagen a usar
      image: nginx:latest

      # pongo la ruta del service (contenedor) a enrutar por https, en este caso webservice_example
      links:
        - webservice

      # Defino las configuraciones del nginx: certificados, puertos, etc (ver ngix/default.conf)
      volumes:
          - ./nginx/:/etc/nginx/conf.d/
          - ./nginx/ssl/:/etc/ssl/certs

      # Defino el puerto seguro a usar
      ports:
        - "443:443"

      restart: always

  mongo:
    image: mongo:5.0.6
    container_name: mongo
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
          limits:
            cpus: "0.50"
            memory: 512M
          reservations:
            cpus: "0.25"
            memory: 128M
    command: --wiredTigerCacheSizeGB 1.5
    #ports:
    #  - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    deploy:
      resources:
          limits:
            cpus: "0.50"
            memory: 512M
          reservations:
            cpus: "0.15"
            memory: 64M
  
volumes:
  config:
  database: