version: '3.8'
services:  
  sidecar_pt:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile.pt
    command: tail -f /dev/null
    volumes:
      - ./:/tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
