version: '3.5'

services:
  openssl:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: cimacorporate/vault_openssl:latest
    volumes:
      - ./certs:/data
    environment:
      - DOMAIN_NAME=www.vault.ecapturedtech.com
    command: >
      openssl req -x509 -nodes -days 825 -newkey rsa:4096 
      -keyout /data/privkey.pem 
      -out /data/fullchain.pem 
      -config /conf/openssl_wisrovi.cnf 
      -extensions v3_req
      
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic_user
      MYSQL_PASSWORD: mautic_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always

  mautic:
    image: mautic/mautic:v4-apache
    # ports:
    #   - "8129:80"
    depends_on:
      - db
    environment:
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_USER=mautic_user
      - MAUTIC_DB_PASSWORD=mautic_password
    volumes:
      - ./data/mautic:/var/www/html
    restart: always  

  mautic-ssl:
    image: nginx:latest
    restart: always
    ports:
      # - "80:80"
      - "8130:443"
    volumes:
      - ./certs:/etc/nginx/certs  # Directorio donde están los certificados SSL
      # - ./nginx/vhost.d:/etc/nginx/vhost.d
      # - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf  # Configuración personalizada de Nginx
    depends_on:
      - mautic
      - openssl


# https://ipa.ecapturedtech.com:8130/