FROM nginx:alpine

RUN apk add --no-cache openssl bash bind-tools

RUN mkdir -p /etc/ssl/certs /etc/ssl/private

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"

COPY nginx/portainer_ttyd/generate_nginx.sh /usr/local/bin/generate_nginx.sh
RUN chmod +x /usr/local/bin/generate_nginx.sh

ENTRYPOINT ["/usr/local/bin/generate_nginx.sh"]