# named volume 'uptime-kuma' is marked as "external" (used by service 'uptime-kuma'), so either remove "external" from volume definition or it needs to be created using: docker volume create uptime-kuma
name: uptime_kuma
services:
    uptime-kuma:
        restart: always
        ports:
            - 7301:3001
        volumes:
            - uptime-kuma:/app/data
        container_name: uptime-kuma
        image: louislam/uptime-kuma:1
volumes:
    uptime-kuma:
