name: Security Scan

on:
  push:
    branches:
      - 001-DEVELOPMENT
      - 002-TEST
      - 003-PRODUCTION
  pull_request:
    branches:
      - 001-DEVELOPMENT
      - 002-TEST
      - 003-PRODUCTION
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para gitleaks

      - name: Run Bandit (SAST)
        run: |
          pip install bandit
          bandit -r . -x ./tests # Escanea todo menos los tests

      - name: Check for Secrets (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
