services:
  nginx2:
    build:
      context: .
      dockerfile: Dockerfile.nginx2
    ports:
      - "50426:80"
      - "50427:443"
    environment:
      - SCALE=4
    networks:
      - dind-network

networks:
  dind-network:
    driver: bridge