server {
    listen 443 ssl;
    server_name wisrovi.duckdns.org;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://server1:80;
    }
}

server {
    listen 80;
    server_name wisrovi.duckdns.org;
    return 301 https://$host$request_uri;
}
