#https://www.guru99.com/crontab-in-linux-with-examples.html
version: '3.3'
services:
  test:
    build: ./test
    container_name: test
    labels:
      "autoheal": "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 2s
      retries: 1
      start_period: 20s
    ports:
      - 33:80
      - 34:3000

  crontab:
    container_name: crontab
    build: ./crontab
    init: true
    environment:
      - CUSTOM_ENV_VAR=foobar
    volumes:
      - ./cron_file/crontab.txt:/var/spool/cron/crontabs/root
    labels:
      "autoheal": "true"
    healthcheck:
      test: ["CMD", "cat", "/home/healthcheck"]
      interval: 30s
      timeout: 2s
      retries: 1
      start_period: 20s

  autoheal:
    container_name: autoheal
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: willfarrell/autoheal
    restart: always


