version: "3"

services:
  datasets:
    image: hurlenko/filebrowser
    container_name: datasets
    volumes:
      - ./jupyter/datasets:/data
      - ./config:/config
    ports:
      - 4443:8080
    environment:
      - PUID=1000
      - PGID=1000
      #  - TZ="Asia/Shanghai"
      - FB_BASEURL=/
      - VIRTUAL_HOST=wisrovi.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=wisrovi.com
      - LETSENCRYPT_EMAIL=wisrovi.rodriguez@gmail.com
    restart: always

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter
    volumes:
      - ./jupyter/notebooks:/tf
      - ./jupyter/datasets:/datasets
      - ./jupyter/models:/models
      - ./jupyter/library:/library
      - ./jupyter/content:/content
    deploy:
      resources:
        reservations:
          # reserves 2048MMB of the RAM memory of the host
          memory: 2048M
          # use the GPU of the host
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    logging:
      driver: "json-file" # json-file syslog none
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 8888:8888
    restart: always

  eyesdcar_train:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: eyesdcar_train
    ports:
      - "3722:80"  # Mapea el puerto 3722 del host al puerto 80 del contenedor
    volumes:
      - ./app:/app  # Monta el código de la aplicación en el contenedor
      - ./jupyter/datasets:/datasets
    environment:
      - PYTHONPATH=/app  # Establece la variable de entorno PYTHONPATH
      - PATH_FILES=/datasets  # Establece la variable de entorno PATH_FILES
    restart: always

    deploy:
      resources:
        reservations:
          # reserves 1024MMB of the RAM memory of the host
          memory: 1024M
    logging:
      driver: "json-file" # json-file syslog none
      options:
        max-size: "200k"
        max-file: "10"
 
