version: "3"

services:
  datasets:
    image: hurlenko/filebrowser
    container_name: datasets
    volumes:
      - ./jupyter/datasets:/data
      - ./config:/config
    ports:
      - 4443:8080
    environment:
      - PUID=1000
      - PGID=1000
      #  - TZ="Asia/Shanghai"
      - FB_BASEURL=/
      - VIRTUAL_HOST=wisrovi.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=wisrovi.com
      - LETSENCRYPT_EMAIL=wisrovi.rodriguez@gmail.com
    restart: always

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter
    volumes:
      - ./jupyter/notebooks:/tf
      - ./jupyter/datasets:/datasets
      - ./jupyter/models:/models
      - ./jupyter/library:/library
    deploy:
      resources:
        reservations:
          # reserves 2048MMB of the RAM memory of the host
          memory: 2048M
          # use the GPU of the host
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    logging:
      driver: "json-file" # json-file syslog none
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 8888:8888
    restart: always
