events {}

http {
    server {
        listen 443 ssl;
        server_name www.vault.ecapturedtech.com;
        
        # Rutas de los certificados SSL
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_pass http://uptimekuma:3001;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Host $host;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }
    }
}