upstream nextcloud-app {
    server app:80;
}

server {
    listen 80;
    server_name ${NEXTCLOUD_DOMAIN};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ${NEXTCLOUD_DOMAIN};

    ssl_certificate /etc/nginx/certs/fullchain.pem; # Debe tener tus certificados SSL
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    client_max_body_size 10G; # Permite la subida de archivos grandes

    location / {
        proxy_pass http://nextcloud-app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_max_temp_file_size 0;
        proxy_buffering off;
        proxy_request_buffering off;
    }
}