# https://labarta.es/como-instalar-mautic-usando-docker-compose/
# https://github.com/jmlcas/mautic/

x-mautic-volumes:
  &mautic-volumes
  - ./data/mautic/config:/var/www/html/config:z
  - ./data/mautic/logs:/var/www/html/var/logs:z
  - ./data/mautic/media/files:/var/www/html/docroot/media/files:z
  - ./data/mautic/media/images:/var/www/html/docroot/media/images:z
#  - ./cron:/opt/mautic/cron:z # Uncomment this line to customize your cron configuration

services:
  db:
    image: mysql:lts
    environment:
      - MYSQL_USER=mautic_db_user
      - MYSQL_PASSWORD=hMqkYeSQ3MOJEOB6
      - MYSQL_DATABASE=mautic_db
      - MYSQL_ROOT_PASSWORD=hMqkYeSQ3MOJEOB6
    volumes:
      - ./data/mautic/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin --user=mautic_db_user --password=hMqkYeSQ3MOJEOB6 ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mautic_web:
    image: mautic/mautic:latest
    ports:
      - 1111:80
    # volumes: *mautic-volumes
    environment:
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_USER=mautic_db_user
      - MAUTIC_DB_PASSWORD=hMqkYeSQ3MOJEOB6
      - MAUTIC_DB_NAME=mautic_db   # 👈 aquí es MAUTIC_DB_NAME, no MAUTIC_DB_DATABASE
      - DOCKER_MAUTIC_LOAD_TEST_DATA=true
      - DOCKER_MAUTIC_RUN_MIGRATIONS=true
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      db:
        condition: service_healthy

  # mautic_cron:
  #   image: mautic/mautic:latest
  #   links:
  #     - db:mysql
  #   volumes: *mautic-volumes
  #   environment:
  #     - DOCKER_MAUTIC_ROLE=mautic_cron
  #     - MAUTIC_MESSENGER_DSN_EMAIL="doctrine://default"
  #     - MAUTIC_MESSENGER_DSN_HIT="doctrine://default"
  #   depends_on:
  #     mautic_web:
  #       condition: service_healthy

  # mautic_worker:
  #   image: mautic/mautic:latest
  #   links:
  #     - db:mysql
  #   volumes: *mautic-volumes
  #   environment:
  #     - DOCKER_MAUTIC_ROLE=mautic_worker
  #   depends_on:
  #     mautic_web:
  #       condition: service_healthy

networks:
  default:
    name: nginx
    external: true