services:
  server1:
    container_name: server1_auth
    image: nginx
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html

  nginx_auth:
    container_name: nginx_auth
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./auth:/etc/nginx/auth:ro
    depends_on:
      - server1
