kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 12741
    listenAddress: "127.0.0.1"
  - containerPort: 81
    hostPort: 12742
    listenAddress: "127.0.0.1"
  - containerPort: 82
    hostPort: 12743
    listenAddress: "127.0.0.1"
  - containerPort: 83
    hostPort: 12744
    listenAddress: "127.0.0.1"
  - containerPort: 84
    hostPort: 12745
    listenAddress: "127.0.0.1"
  - containerPort: 85
    hostPort: 12746
    listenAddress: "127.0.0.1"
  - containerPort: 86
    hostPort: 12747
    listenAddress: "127.0.0.1"
  - containerPort: 87
    hostPort: 12748
    listenAddress: "127.0.0.1"
  - containerPort: 88
    hostPort: 12749
    listenAddress: "127.0.0.1"
  - containerPort: 89
    hostPort: 12750
    listenAddress: "127.0.0.1"
  - containerPort: 90
    hostPort: 12751
    listenAddress: "127.0.0.1"
  - containerPort: 91
    hostPort: 12752
    listenAddress: "127.0.0.1"
  - containerPort: 92
    hostPort: 12753
    listenAddress: "127.0.0.1"
  - containerPort: 93
    hostPort: 12754
    listenAddress: "127.0.0.1"
  - containerPort: 94
    hostPort: 12755
    listenAddress: "127.0.0.1"
  - containerPort: 95
    hostPort: 12756
    listenAddress: "127.0.0.1"
  - containerPort: 96
    hostPort: 12757
    listenAddress: "127.0.0.1"
  - containerPort: 97
    hostPort: 12758
    listenAddress: "127.0.0.1"
  - containerPort: 98
    hostPort: 12759
    listenAddress: "127.0.0.1"
  - containerPort: 99
    hostPort: 12760
    listenAddress: "127.0.0.1"
  - containerPort: 100
    hostPort: 12761
    listenAddress: "127.0.0.1"
  extraMounts:
  - hostPath: /dev/nvidia0
    containerPath: /dev/nvidia0
  - hostPath: /dev/nvidiactl
    containerPath: /dev/nvidiactl
  - hostPath: /dev/nvidiamodeset
    containerPath: /dev/nvidiamodeset
  - hostPath: /dev/nvidia-uvm
    containerPath: /dev/nvidia-uvm
  - hostPath: /dev/nvidia-uvm-tools
    containerPath: /dev/nvidia-uvm-tools
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "nvidia.com/gpu.present=true"
- role: worker
  extraMounts:
  - hostPath: /dev/nvidia0
    containerPath: /dev/nvidia0
  - hostPath: /dev/nvidiactl
    containerPath: /dev/nvidiactl
  - hostPath: /dev/nvidiamodeset
    containerPath: /dev/nvidiamodeset
  - hostPath: /dev/nvidia-uvm
    containerPath: /dev/nvidia-uvm
  - hostPath: /dev/nvidia-uvm-tools
    containerPath: /dev/nvidia-uvm-tools
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
- role: worker
  extraMounts:
  - hostPath: /dev/nvidia0
    containerPath: /dev/nvidia0
  - hostPath: /dev/nvidiactl
    containerPath: /dev/nvidiactl
  - hostPath: /dev/nvidiamodeset
    containerPath: /dev/nvidiamodeset
  - hostPath: /dev/nvidia-uvm
    containerPath: /dev/nvidia-uvm
  - hostPath: /dev/nvidia-uvm-tools
    containerPath: /dev/nvidia-uvm-tools
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
- role: worker
  extraMounts:
  - hostPath: /dev/nvidia0
    containerPath: /dev/nvidia0
  - hostPath: /dev/nvidiactl
    containerPath: /dev/nvidiactl
  - hostPath: /dev/nvidiamodeset
    containerPath: /dev/nvidiamodeset
  - hostPath: /dev/nvidia-uvm
    containerPath: /dev/nvidia-uvm
  - hostPath: /dev/nvidia-uvm-tools
    containerPath: /dev/nvidia-uvm-tools
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
- role: worker
  extraMounts:
  - hostPath: /dev/nvidia0
    containerPath: /dev/nvidia0
  - hostPath: /dev/nvidiactl
    containerPath: /dev/nvidiactl
  - hostPath: /dev/nvidiamodeset
    containerPath: /dev/nvidiamodeset
  - hostPath: /dev/nvidia-uvm
    containerPath: /dev/nvidia-uvm
  - hostPath: /dev/nvidia-uvm-tools
    containerPath: /dev/nvidia-uvm-tools
  - hostPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
  - hostPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    containerPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1