FROM wisrovi/agents:gpu-slim-dvc

SHELL ["bash", "-c"]

COPY src/scripts/api/requirements.txt /app/requirements.txt
COPY worker.py /app/worker.py
RUN python -m pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app
COPY .git /app/.git
COPY .dvc /app/.dvc
COPY dvc.yaml /app/dvc.yaml
COPY dvc.lock /app/dvc.lock

COPY worker.py /app

COPY src /app/src
