version: '3.8'
services:

  ssh-mongodb:
    image: mongo:6.0
    container_name: mongo
    restart: always

  ssh-opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    restart: always

  ssh-graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=1234
      - GRAYLOG_ROOT_PASSWORD_SHA2=03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9100/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    links:
      - ssh-mongodb
      - ssh-opensearch
    depends_on:
      - ssh-mongodb
      - ssh-opensearch
    ports:
      - "9100:9000"
      - "12201:12201/udp"
    restart: always