version: '3.3'
services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - 1717:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home:/home
