version: '3.3'
services:
    #test:
    #    build: ./test
    #    container_name: test
    #    labels:
    #        "autoheal": "true"

    autoheal:
        container_name: autoheal
        restart: always
        environment:
            - AUTOHEAL_INTERVAL=10
            - CURL_TIMEOUT=30
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: willfarrell/autoheal