version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "1717:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: wisrovi.rodriguez@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: