version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    container_name: fireflyiii
    restart: always
    volumes:
      - ./firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 83:8080
    depends_on:
      - db
      
  db:
    image: mariadb    
    container_name: database_fireflyiii
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - ./firefly_iii_db:/var/lib/mysql      
    #ports:
    #  - 3306:3306