version: '3.8'
services:
  docker_in_docker:
    container_name: docker_in_docker
    build: .
    ports:
      - 50422:22
    volumes:
      # for docker
      - /var/run/docker.sock:/var/run/docker.sock   # Permite a Jenkins interactuar con Docker en el host
      - ./files:/app
    working_dir: /app
    user: root
    restart: always
    environment:
      - TZ=Europe/Madrid # Ajusta la zona horaria a tu ubicación
