apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-worker4
spec:
  nodeSelector:
    worker: worker4
  restartPolicy: Never
  containers:
  - name: gpu-container
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["/usr/local/cuda/bin/nvidia-smi"]