version: "3.8"

services:
  dvc-minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=DVC
      - MINIO_ROOT_PASSWORD=uTAntEMTuVpcJucNjOJm
      # - MINIO_DEFAULT_BUCKETS=datasets
    ports:
      - "30706:9000" # Port S3 : 30702
      - "30707:9001" # Admin port: 30703
    volumes:
      #- ./DVC_data:/data
      - /mnt/DVC_tmp/DVC_data:/data

  docs:
    image: nginx:alpine
    restart: always
    ports:
      - "30705:80"
    volumes:
      - ./docs/_build/html:/usr/share/nginx/html

