# named volume 'uptime-kuma' is marked as "external" (used by service 'uptime-kuma'), so either remove "external" from volume definition or it needs to be created using: docker volume create uptime-kuma
name: uptime_kuma
services:
    uptimekuma:
        restart: always
        # ports:
        #     - 7301:3001
        volumes:
            - uptime-kuma:/app/data
        container_name: uptime-kuma
        image: louislam/uptime-kuma:1

    uptimekuma-ssl:
        image: nginx:latest
        restart: always
        ports:
            # - "80:80"
            - "3001:443"
        volumes:
            - ./certs:/etc/nginx/certs  # Directorio donde están los certificados SSL
            # - ./nginx/vhost.d:/etc/nginx/vhost.d
            # - ./nginx/html:/usr/share/nginx/html
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf  # Configuración personalizada de Nginx
        depends_on:
            - uptimekuma

    
volumes:
    uptime-kuma:
    
networks:
  default:
    name: nginx
    external: true
