  server1:
    container_name: server1
    image: nginx
    volumes:
      - ./html/index.1.html:/usr/share/nginx/html/index.html
    #ports:
    #  - 80:80

  server2:
    container_name: server2
    image: nginx
    volumes:
      - ./html/index.2.html:/usr/share/nginx/html/index.html
    #ports:
    #  - 80:80

  server3:
    container_name: server3
    image: nginx
    volumes:
      - ./html/index.3.html:/usr/share/nginx/html/index.html
    #ports:
    #  - 80:80

  nginx:
    container_name: nginx_demo
    image: nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80