# Generated by Django 4.1 on 2022-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=50)),
                ('vence', models.DateTimeField()),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=20)),
                ('path_instalation', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('h_c', models.CharField(default='', max_length=200)),
                ('h_h', models.CharField(default='', max_length=200)),
                ('h_m5', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
