version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: wisrovi/postgres:v1
    environment:
      - POSTGRES_USER=perseus
      - POSTGRES_PASSWORD=7bPnWmNtzNF36c8J8yWN
      - POSTGRES_DB=perseus
    volumes: 
      - perseus-db:/var/lib/postgresql/data
    deploy:
      resources:
          limits:
            cpus: 0.50
            memory: 1024M
          reservations:
            cpus: 0.25
            memory: 512M
    ports:
      - '5432:5432'
    restart: always
    networks:
      - perseus-net

networks:
  perseus-net:
    driver: bridge

volumes:
  perseus-db:
    driver: local
