apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  replicas: 2  # Número inicial de réplicas
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      runtimeClassName: nvidia  # REQUIRED IN RKE2
      volumes:
        - name: ollama-volume
          persistentVolumeClaim:
            claimName: ollama-pvc
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/ai-worker: "true"
      # imagePullSecrets:
      #   - name: harbor-secret  # We used the name we validated earlier (wisrovi
      containers:
      - name: ollama-container
        image: ollama/ollama:latest 
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_NUM_PARALLEL
          value: "2"
        - name: OLLAMA_MAX_LOADED_MODELS
          value: "1"
        resources:
          limits:
            memory: "12Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          requests:
            memory: "8Gi"
            cpu: "1"
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: "/root/.ollama"
            name: ollama-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: local-path  # production: local-storage
  storageClassName: standard  # development: standard
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434

# prueba rapida para ver si los pods de Ollama están funcionando correctamente:
# kubectl port-forward --address 0.0.0.0 svc/ollama-service 11434:11434
# curl http://localhost:11434/api/tags

# docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
# ir a http://localhost:3000/ para acceder a la interfaz de Open WebUI, que se conecta al servicio de Ollama en el puerto 11434.

# opcion oficial:
# https://github.com/otwld/ollama-helm
