# Generated by Django 4.1 on 2022-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_mac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='computername',
            field=models.CharField(default='', max_length=30),
        ),
    ]
